In [1]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = np.sum(gfg)

# ii. Sum of all elements row-wise
row_sum = np.sum(gfg, axis=1)

# iii. Sum of all elements column-wise
col_sum = np.sum(gfg, axis=0)

print("Sum of all elements:", total_sum)
print("Sum of all elements row-wise:\n", row_sum)
print("Sum of all elements column-wise:\n", col_sum)

Sum of all elements: 45
Sum of all elements row-wise:
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:
 [[20  9 16]]


In [3]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_4 = np.sort(array)[:4]

# iv. 5 largest elements
largest_5 = np.sort(array)[-5:]

print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 Smallest elements:", smallest_4)
print("5 Largest elements:", largest_5)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 Smallest elements: [10 16 16 52]
5 Largest elements: [ 16  52  54  62 453]


In [5]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_elements = array[array == array.astype(int)]

# ii. Float elements only
float_elements = array[array != array.astype(int)]

print("Integer elements only:", integer_elements)
print("Float elements only:", float_elements)

Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [7]:
import numpy as np

# a) Generate sales dataset
X = ord('V') + ord('G')
sales = np.array([X, X+50, X+100, X+150, X+200])

print("Sales data:", sales)

Sales data: [157 207 257 307 357]


In [9]:
# b) Compute personalized tax rate and apply it
tax_rate = ((X % 5) + 5) / 100
taxed_sales = sales * tax_rate

print("Personalized tax rate:", tax_rate)
print("Tax applied on sales:", taxed_sales)

Personalized tax rate: 0.07
Tax applied on sales: [10.99 14.49 17.99 21.49 24.99]


In [11]:
# c) Adjust sales based on discount
discounted_sales = np.where(sales < X+100, sales * 0.95, sales * 0.90)

print("Discounted sales:", discounted_sales)

Discounted sales: [149.15 196.65 231.3  276.3  321.3 ]


In [13]:
# d) Expand sales data for multiple weeks
weeks = 3
weekly_sales = np.tile(sales, (weeks, 1))

week_multipliers = np.array([1.00, 1.02, 1.04]).reshape(3, 1)
adjusted_weekly_sales = weekly_sales * week_multipliers

print("Weekly sales data:\n", adjusted_weekly_sales)

Weekly sales data:
 [[157.   207.   257.   307.   357.  ]
 [160.14 211.14 262.14 313.14 364.14]
 [163.28 215.28 267.28 319.28 371.28]]


In [15]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)
y1, y2, y3, y4 = x**2, np.sin(x), np.exp(x), np.log(np.abs(x) + 1)

plt.figure(figsize=(10, 6))
plt.plot(x, y1, label=r"
", color="blue")
plt.plot(x, y2, label=r"
", color="red")
plt.plot(x, y3, label=r"
", color="green")
plt.plot(x, y4, label=r"
", color="purple")

plt.title("Mathematical Functions Visualization", fontsize=14)
plt.xlabel("x values", fontsize=12)
plt.ylabel("y values", fontsize=12)
plt.axhline(0, color='black', linewidth=0.5)
plt.axvline(0, color='black', linewidth=0.5)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend()
plt.show()

SyntaxError: unterminated string literal (detected at line 8) (682353949.py, line 8)